version: '3.8'

services:
  pozitiv:
    image: tilzam/ar_finance:latest
    container_name: ar_finance_container
    ports:
      - "3000:3000"  # Map port 3000 on the host to port 3000 in the container
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ar_finance?schema=public  # Environment variable for database URL
      - NODE_ENV=production
    depends_on:
      - db
    restart: always  # Always restart the container if it stops

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ar_finance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always  # Always restart the container if it stops

volumes:
  postgres_data:
    driver: local

networks:
  default:
    driver: bridge
