import { PrismaClient } from "@prisma/client"
import type { zSection } from "@/types/content.schema"

const prisma = new PrismaClient()

async function seedSections() {
  const sections: zSection[] = [
    {
      id: "hero",
      sectionName_ru: null,
      sectionName_en: null,
      sectionName_ky: null,
      heading_ru: "Мы делаем бухгалтерию простой",
      heading_en: "We make accounting simple",
      heading_ky: "Биз бухгалтердик эсепти жөнөкөйлөштүрөбүз",
      subheading_ru:
        "Оставьте заявку, чтобы узнать, как наши решения могут упростить Ваш бухгалтерский учет",
      subheading_en:
        "Leave a request to find out how our solutions can simplify your accounting",
      subheading_ky:
        "Биздин чечимдер бухгалтердик эсепти кантип жөнөкөйлөштүрө аларын билүү үчүн өтүнүч калтырыңыз",
      primaryButton_ru: "Оставить заявку",
      primaryButton_en: "Submit your application",
      primaryButton_ky: "Өтүнмөңүздү тапшырыңыз",
      secondaryButton_ru: null,
      secondaryButton_en: null,
      secondaryButton_ky: null,
      cards: [],
    },
    {
      id: "about-us",
      sectionName_ru: "О нас",
      sectionName_en: "About us",
      sectionName_ky: "Биз жөнүндө",
      heading_ru: "Мы - AR Finance",
      heading_en: "We are AR Finance",
      heading_ky: "Биз AR Finance",
      subheading_ru:
        "Наша компания специализируется на предоставлении высококачественных профессиональных бухгалтерских услуг для Вашего бизнеса! Наша цель - помочь Вам сфокусироваться на росте Вашего бизнеса, обеспечивая надежное и эффективное финансовое сопровождение",
      subheading_en:
        "Our company specializes in providing high-quality professional accounting services for your business! Our goal is to help you focus on the growth of your business by providing reliable and effective financial support",
      subheading_ky:
        "Биздин компания сиздин бизнесиңиз үчүн жогорку сапаттагы кесипкөй бухгалтердик кызматтарды көрсөтүүгө адистешкен! Биздин максат ишенимдүү жана натыйжалуу каржылык колдоо көрсөтүү аркылуу бизнесиңиздин өсүшүнө көңүл бурууга жардам берүү",
      primaryButton_ru: null,
      primaryButton_en: null,
      primaryButton_ky: null,
      secondaryButton_ru: null,
      secondaryButton_en: null,
      secondaryButton_ky: null,
      cards: [
        {
          id: "about-us-card-1",
          sectionId: "about-us",
          title_ru: null,
          title_en: null,
          title_ky: null,
          description_ru: null,
          description_en: null,
          description_ky: null,
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: "/assets/about/image1.jpg",
        },
        {
          id: "about-us-card-2",
          sectionId: "about-us",
          title_ru: null,
          title_en: null,
          title_ky: null,
          description_ru: null,
          description_en: null,
          description_ky: null,
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: "/assets/about/image2.jpg",
        },
        {
          id: "about-us-card-3",
          sectionId: "about-us",
          title_ru: null,
          title_en: null,
          title_ky: null,
          description_ru: null,
          description_en: null,
          description_ky: null,
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: "/assets/about/image3.jpg",
        },
        {
          id: "about-us-card-4",
          sectionId: "about-us",
          title_ru: null,
          title_en: null,
          title_ky: null,
          description_ru: null,
          description_en: null,
          description_ky: null,
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: "/assets/about/image4.jpg",
        },
        {
          id: "about-us-card-5",
          sectionId: "about-us",
          title_ru: null,
          title_en: null,
          title_ky: null,
          description_ru: null,
          description_en: null,
          description_ky: null,
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: "/assets/about/image5.jpg",
        },
      ],
    },
    {
      id: "why-us",
      sectionName_ru: "Почему мы?",
      sectionName_en: "Why choose us?",
      sectionName_ky: "Эмне үчүн биз?",
      heading_ru: null,
      heading_en: null,
      heading_ky: null,
      subheading_ru: null,
      subheading_en: null,
      subheading_ky: null,
      primaryButton_ru: null,
      primaryButton_en: null,
      primaryButton_ky: null,
      secondaryButton_ru: null,
      secondaryButton_en: null,
      secondaryButton_ky: null,
      cards: [
        {
          id: "why-us-card-1",
          sectionId: "why-us",
          title_ru: "Профессионализм",
          title_en: "Professionalism",
          title_ky: "Профессионализм",
          description_ru:
            "Опытные бухгалтеры и налоговые консультанты с многолетним стажем",
          description_en:
            "Experienced accountants and tax consultants with a long experience",
          description_ky:
            "Биз бухгалтердик байлдырмалар жана налогдарын байлдырмалары с мүмкүн саламдардым",
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: null,
        },
        {
          id: "why-us-card-2",
          sectionId: "why-us",
          title_ru: "Надежность",
          title_en: "Reliability",
          title_ky: "Надежность",
          description_ru:
            "Мы гарантируем точность и своевременность выполнения всех работ",
          description_en:
            "We guarantee accuracy and timely completion of all our work",
          description_ky:
            "Биз бул жердүнүүдүн сүрөткөрүнө үчүн жалпы жараксыздым",
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: null,
        },
        {
          id: "why-us-card-3",
          sectionId: "why-us",
          title_ru: "Индивидуальный подход",
          title_en: "Individual approach",
          title_ky: "Индивидуальный подход",
          description_ru:
            "Учитываем особенности вашего бизнеса и предлагаем наилучшие решения",
          description_en:
            "We take into account the specifics of your business and offer the best solutions",
          description_ky:
            "Биз бул жердүнүүдүн сүрөткөрүнө үчүн жалпы жараксыздым",
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: null,
        },
        {
          id: "why-us-card-4",
          sectionId: "why-us",
          title_ru: "Конфиденциальность",
          title_en: "Confidentiality",
          title_ky: "Конфиденциальность",
          description_ru:
            "Обеспечиваем полную защиту вашей финансовой информации",
          description_en:
            "We ensure full confidentiality of your financial information",
          description_ky:
            "Биз бул жердүнүүдүн сүрөткөрүнө үчүн жалпы жараксыздым",
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: null,
        },
      ],
    },
    {
      id: "cta",
      sectionName_ru: null,
      sectionName_en: null,
      sectionName_ky: null,
      heading_ru: "Спецпредложение для стартаперов",
      heading_en: "Special offer for startups",
      heading_ky: "Стартаптар үчүн атайын сунуш",
      subheading_ru:
        "Для новых клиентов - стартапов мы предлагаем бесплатную консультацию и бесплатный аудит ваших текущих бухгалтерских процессов. Мы оценим вашу ситуацию и предложим наиболее эффективные решения для вашего бизнеса.",
      subheading_en:
        "For new clients - startups we offer free consultation and free audit of your current accounting processes. We assess your situation and suggest the most effective solutions for your business.",
      subheading_ky:
        "Жаңы кардарлар - стартаптар үчүн биз акысыз консультацияларды жана учурдагы бухгалтердик процесстердин акысыз аудитин сунуштайбыз. Биз сиздин абалыңызды баалайбыз жана бизнесиңиз үчүн эң эффективдүү чечимдерди сунуштайбыз.",
      primaryButton_ru: "Получить предложение",
      primaryButton_en: "Get an offer",
      primaryButton_ky: "Сунуш алыңыз",
      secondaryButton_ru: "Подробнее",
      secondaryButton_en: "Learn more",
      secondaryButton_ky: "Көбүрөөк билүү",
      cards: [],
    },
    {
      id: "our-services",
      sectionName_ru: "Наши услуги",
      sectionName_en: "Our services",
      sectionName_ky: "Биздин кызматтар",
      heading_ru: "Получите персонализированное решение",
      heading_en: "Get personalized solutions",
      heading_ky: "Жекече чечимди алыңыз",
      subheading_ru:
        "Мы берем на себя все аспекты ведения бухгалтерского учета, чтобы вы могли сосредоточиться на вашем бизнесе. В наши услуги входят:",
      subheading_en:
        "We take care of all aspects of accounting management to make you focus on your business. Our services include:",
      subheading_ky:
        "Биз бухгалтердик эсептин бардык аспектилерине кам көрөбүз, ошондуктан сиздин бизнесиңизге көңүл буруңуз. Биздин кызматтарга төмөнкүлөр кирет:",
      primaryButton_ru: null,
      primaryButton_en: null,
      primaryButton_ky: null,
      secondaryButton_ru: null,
      secondaryButton_en: null,
      secondaryButton_ky: null,
      cards: [
        {
          id: "our-services-card-1",
          sectionId: "our-services",
          title_ru: "Бухгалтерский учет",
          title_en: "Accounting",
          title_ky: "Бухгалтерский учет",
          description_ru:
            "Мы берем на себя все аспекты ведения бухгалтерского учета, чтобы вы могли сосредоточиться на вашем бизнесе. В наши услуги входят:",
          description_en:
            "We take care of all aspects of accounting management to make you focus on your business. Our services include:",
          description_ky:
            "Биз бухгалтердик эсептин бардык аспектилерине кам көрөбүз, ошондуктан сиздин бизнесиңизге көңүл буруңуз. Биздин кызматтарга төмөнкүлөр кирет:",
          extra_ru: "10 000 сом",
          extra_en: "10 000 som",
          extra_ky: "10 000 сом",
          bullets_ru: [
            "Ведение первичной документации",
            "Расчет заработной платы",
            "Учет доходов и расходов",
            "Подготовка бухгалтерской отчетности",
            "Ведение первичной документации",
            "Расчет заработной платы",
            "Учет доходов и расходов",
            "Подготовка бухгалтерской отчетности",
          ],
          bullets_en: [
            "Maintaining primary documentation",
            "Payroll calculation",
            "Accounting for income and expenses",
            "Preparation of financial statements",
            "Maintaining primary documentation",
            "Payroll calculation",
            "Accounting for income and expenses",
            "Preparation of financial statements",
          ],
          bullets_ky: [
            "Баштапкы документацияны жүргүзүү",
            "Эмгек акыларды эсептөө",
            "Киреше жана чыгашаларды эсепке алуу",
            "Финансылык отчеттуулукту түзүү",
            "Баштапкы документацияны жүргүзүү",
            "Эмгек акысын эсептөө",
            "Кирешелердин жана чыгашалардын эсеби",
            "Финансылык отчеттуулукту түзүү",
          ],
          image: null,
        },
        {
          id: "our-services-card-2",
          sectionId: "our-services",
          title_ru: "Бухгалтерский учет",
          title_en: "Accounting",
          title_ky: "Бухгалтерский учет",
          description_ru:
            "Мы берем на себя все аспекты ведения бухгалтерского учета, чтобы вы могли сосредоточиться на вашем бизнесе. В наши услуги входят:",
          description_en:
            "We take care of all aspects of accounting management to make you focus on your business. Our services include:",
          description_ky:
            "Биз бухгалтердик эсептин бардык аспектилерине кам көрөбүз, ошондуктан сиздин бизнесиңизге көңүл буруңуз. Биздин кызматтарга төмөнкүлөр кирет:",
          extra_ru: "10 000 сом",
          extra_en: "10 000 som",
          extra_ky: "10 000 сом",
          bullets_ru: [
            "Ведение первичной документации",
            "Расчет заработной платы",
            "Учет доходов и расходов",
            "Подготовка бухгалтерской отчетности",
            "Ведение первичной документации",
            "Расчет заработной платы",
            "Учет доходов и расходов",
            "Подготовка бухгалтерской отчетности",
          ],
          bullets_en: [
            "Maintaining primary documentation",
            "Payroll calculation",
            "Accounting for income and expenses",
            "Preparation of financial statements",
            "Maintaining primary documentation",
            "Payroll calculation",
            "Accounting for income and expenses",
            "Preparation of financial statements",
          ],
          bullets_ky: [
            "Баштапкы документацияны жүргүзүү",
            "Эмгек акыларды эсептөө",
            "Киреше жана чыгашаларды эсепке алуу",
            "Финансылык отчеттуулукту түзүү",
            "Баштапкы документацияны жүргүзүү",
            "Эмгек акысын эсептөө",
            "Кирешелердин жана чыгашалардын эсеби",
            "Финансылык отчеттуулукту түзүү",
          ],
          image: null,
        },
        {
          id: "our-services-card-3",
          sectionId: "our-services",
          title_ru: "Бухгалтерский учет",
          title_en: "Accounting",
          title_ky: "Бухгалтерский учет",
          description_ru:
            "Мы берем на себя все аспекты ведения бухгалтерского учета, чтобы вы могли сосредоточиться на вашем бизнесе. В наши услуги входят:",
          description_en:
            "We take care of all aspects of accounting management to make you focus on your business. Our services include:",
          description_ky:
            "Биз бухгалтердик эсептин бардык аспектилерине кам көрөбүз, ошондуктан сиздин бизнесиңизге көңүл буруңуз. Биздин кызматтарга төмөнкүлөр кирет:",
          extra_ru: "10 000 сом",
          extra_en: "10 000 som",
          extra_ky: "10 000 сом",
          bullets_ru: [
            "Ведение первичной документации",
            "Расчет заработной платы",
            "Учет доходов и расходов",
            "Подготовка бухгалтерской отчетности",
            "Ведение первичной документации",
            "Расчет заработной платы",
            "Учет доходов и расходов",
            "Подготовка бухгалтерской отчетности",
          ],
          bullets_en: [
            "Maintaining primary documentation",
            "Payroll calculation",
            "Accounting for income and expenses",
            "Preparation of financial statements",
            "Maintaining primary documentation",
            "Payroll calculation",
            "Accounting for income and expenses",
            "Preparation of financial statements",
          ],
          bullets_ky: [
            "Баштапкы документацияны жүргүзүү",
            "Эмгек акыларды эсептөө",
            "Киреше жана чыгашаларды эсепке алуу",
            "Финансылык отчеттуулукту түзүү",
            "Баштапкы документацияны жүргүзүү",
            "Эмгек акысын эсептөө",
            "Кирешелердин жана чыгашалардын эсеби",
            "Финансылык отчеттуулукту түзүү",
          ],
          image: null,
        },
        {
          id: "our-services-card-4",
          sectionId: "our-services",
          title_ru: "Бухгалтерский учет",
          title_en: "Accounting",
          title_ky: "Бухгалтерский учет",
          description_ru:
            "Мы берем на себя все аспекты ведения бухгалтерского учета, чтобы вы могли сосредоточиться на вашем бизнесе. В наши услуги входят:",
          description_en:
            "We take care of all aspects of accounting management to make you focus on your business. Our services include:",
          description_ky:
            "Биз бухгалтердик эсептин бардык аспектилерине кам көрөбүз, ошондуктан сиздин бизнесиңизге көңүл буруңуз. Биздин кызматтарга төмөнкүлөр кирет:",
          extra_ru: "10 000 сом",
          extra_en: "10 000 som",
          extra_ky: "10 000 сом",
          bullets_ru: [
            "Ведение первичной документации",
            "Расчет заработной платы",
            "Учет доходов и расходов",
            "Подготовка бухгалтерской отчетности",
            "Ведение первичной документации",
            "Расчет заработной платы",
            "Учет доходов и расходов",
            "Подготовка бухгалтерской отчетности",
          ],
          bullets_en: [
            "Maintaining primary documentation",
            "Payroll calculation",
            "Accounting for income and expenses",
            "Preparation of financial statements",
            "Maintaining primary documentation",
            "Payroll calculation",
            "Accounting for income and expenses",
            "Preparation of financial statements",
          ],
          bullets_ky: [
            "Баштапкы документацияны жүргүзүү",
            "Эмгек акыларды эсептөө",
            "Киреше жана чыгашаларды эсепке алуу",
            "Финансылык отчеттуулукту түзүү",
            "Баштапкы документацияны жүргүзүү",
            "Эмгек акысын эсептөө",
            "Кирешелердин жана чыгашалардын эсеби",
            "Финансылык отчеттуулукту түзүү",
          ],
          image: null,
        },
      ],
    },
    {
      id: "plans",
      sectionName_ru: "Тарифы",
      sectionName_en: "Plans",
      sectionName_ky: "Тарифтер",
      heading_ru: "Прозрачные и доступные цены для вашего бизнеса",
      heading_en: "Transparent and available prices for your business",
      heading_ky: "Ар кандай бизнес үчүн ачык жана жеткиликтүү баалар",
      subheading_ru:
        "Мы предлагаем различные тарифные планы, чтобы вы могли выбрать тот, который наилучшим образом соответствует вашим потребностям и бюджету. Наши тарифы включают все необходимые услуги для ведения бухгалтерского учета, налогового консультирования и финансового планирования.",
      subheading_en:
        "We offer various tariff plans to help you choose the best way to meet your needs and budget. Our plans include all necessary services for accounting management, tax advisory and financial planning.",
      subheading_ky:
        "Биз сиздин муктаждыктарыңызга жана бюджетиңизге эң туура келгенин тандап алуу үчүн ар кандай пландарды сунуштайбыз. Биздин тарифтер бухгалтердик эсеп, салыктык консалтинг жана финансылык пландаштыруу боюнча бардык зарыл кызматтарды камтыйт.",
      primaryButton_ru: "Выбрать тариф",
      primaryButton_en: "Choose a plan",
      primaryButton_ky: "Тарифты таңдаңыз",
      secondaryButton_ru: null,
      secondaryButton_en: null,
      secondaryButton_ky: null,
      cards: [
        {
          id: "plans-card-1",
          sectionId: "plans",
          title_ru: "Базовый",
          title_en: "Basic",
          title_ky: "Базовый",
          description_ru: "Идеально подходит для малого бизнеса и стартапов",
          description_en: "Ideal for small businesses and startups",
          description_ky:
            "Бизнес аркылууларда болгону жана стартаптарда болгону",
          extra_ru: "от 7 900 сом",
          extra_en: "from 7,900 som",
          extra_ky: "7 900 сомдон",
          bullets_ru: [
            "Ведение бухгалтерского учета",
            "Подготовка и сдача отчетности",
            "Консультации по основным вопросам налогообложения",
            "Поддержка по email",
          ],
          bullets_en: [
            "Accounting",
            "Preparation and submission of reports",
            "Consultations on basic tax issues",
            "Support by email",
          ],
          bullets_ky: [
            "Бухгалтердик эсеп",
            "Отчетторду даярдоо жана берүү",
            "Салыктын негизги маселелери боюнча консультациялар",
            "Электрондук почта аркылуу колдоо",
          ],
          image: "/assets/plan-icons/zap.png",
        },
        {
          id: "plans-card-2",
          sectionId: "plans",
          title_ru: "Стандарт",
          title_en: "Standard",
          title_ky: "Стандарт",
          description_ru: "Оптимальный выбор для развивающихся компаний",
          description_en: "Optimal for growing businesses",
          description_ky: "Өнүгүп жаткан компаниялар үчүн оптималдуу тандоо",
          extra_ru: "от 17 900 сом",
          extra_en: "from 17,900 som",
          extra_ky: "17 900 сомдон",
          bullets_ru: [
            "Все перечисленное в тарифе 'Базовый', плюс:",
            "Поддержка по email",
            "Поддержка по email",
            "Поддержка по email",
          ],
          bullets_en: [
            "Everything listed in the 'Basic' plan, plus:",
            "Support by email",
            "Support by email",
            "Support by email",
          ],
          bullets_ky: [
            "«Базовый» тарифте жазылгандардын баары, жана:",
            "Электрондук почта аркылуу колдоо",
            "Электрондук почта аркылуу колдоо",
            "Электрондук почта аркылуу колдоо",
          ],
          image: "/assets/plan-icons/cluster.png",
        },
        {
          id: "plans-card-3",
          sectionId: "plans",
          title_ru: "Премиум",
          title_en: "Premium",
          title_ky: "Премиум",
          description_ru:
            "Для компаний, которым нужен комплексный подход к бухгалтерскому учету и налоговому планированию",
          description_en:
            "For businesses with complex accounting and tax planning needs",
          description_ky:
            "Бухгалтердик эсепке жана салыкты пландаштырууга комплекстүү мамилени талап кылган компаниялар үчүн",
          extra_ru: "от 37 900 сом",
          extra_en: "from 37,900 som",
          extra_ky: "37 900 сомдон",
          bullets_ru: [
            "Все перечисленное в тарифе 'Стандарт', плюс:",
            "Подготовка и сдача отчетности",
            "Подготовка и сдача отчетности",
            "Подготовка и сдача отчетности",
          ],
          bullets_en: [
            "Everything listed in the 'Standard' plan, plus:",
            "Preparation and submission of reports",
            "Preparation and submission of reports",
            "Preparation and submission of reports",
          ],
          bullets_ky: [
            "«Стандарт» тарифте жазылгандардын баары, жана:",
            "Отчетторду даярдоо жана берүү",
            "Отчетторду даярдоо жана берүү",
            "Отчетторду даярдоо жана берүү",
          ],
          image: "/assets/plan-icons/star.png",
        },
      ],
    },
    {
      id: "calculator",
      sectionName_ru: "Калькулятор",
      sectionName_en: "Calculator",
      sectionName_ky: "Калькулятор",
      heading_ru: "Рассчитайте стоимость наших услуг",
      heading_en: "Calculate our cost",
      heading_ky: "Биздин кызматтардын баасын эсептеп алыңыз",
      subheading_ru:
        "Мы понимаем, что каждый бизнес уникален и требует индивидуального подхода. Чтобы упростить процесс выбора и расчета стоимости наших услуг, мы предлагаем воспользоваться калькулятором услуг. Это позволит вам быстро и удобно узнать ориентировочную цену наших бухгалтерских услуг, исходя из потребностей вашего бизнеса.",
      subheading_en:
        "We understand that every business is unique and requires an individual approach. To simplify the process of selecting and calculating the cost of our services, we suggest using a service calculator. This will allow you to quickly and conveniently find out the estimated price of our accounting services based on the needs of your business.",
      subheading_ky:
        "Ар бир бизнес уникалдуу экенин жана жеке мамилени талап кылаарын түшүнөбүз. Биздин кызматтардын баасын тандоо жана эсептөө процессин жөнөкөйлөтүү үчүн биз кызмат калькуляторун колдонууну сунуштайбыз. Бул сиздин бизнесиңиздин муктаждыктарына жараша биздин бухгалтердик кызматтардын болжолдуу баасын тез жана ыңгайлуу билүүгө мүмкүндүк берет.",
      primaryButton_ru: null,
      primaryButton_en: null,
      primaryButton_ky: null,
      secondaryButton_ru: null,
      secondaryButton_en: null,
      secondaryButton_ky: null,
      cards: [],
    },
    {
      id: "blog",
      sectionName_ru: "Блог",
      sectionName_en: "Blog",
      sectionName_ky: "Блог",
      heading_ru: "Последние статьи",
      heading_en: "Latest articles",
      heading_ky: "Акыркы макалалар",
      subheading_ru:
        "Здесь вы найдете последние новости, полезные советы и экспертные мнения по вопросам бухгалтерии и финансов. Мы делимся знаниями и опытом, чтобы помочь вашему бизнесу расти и процветать.",
      subheading_en:
        "Here you can find the latest news, useful advice and expert opinions on accounting and finance. We share knowledge and experience to help your business grow and succeed.",
      subheading_ky:
        "Бул жерден сиз бухгалтердик эсеп жана финансы боюнча акыркы жаңылыктарды, пайдалуу кеңештерди жана эксперттердин пикирлерин таба аласыз. Биз сиздин бизнесиңиздин өнүгүшүнө жана гүлдөшүнө жардам берүү үчүн билим жана тажрыйба менен бөлүшөбүз.",
      primaryButton_ru: "Смотреть все статьи",
      primaryButton_en: "View all articles",
      primaryButton_ky: "Бардык макалаларды көрүү",
      secondaryButton_ru: null,
      secondaryButton_en: null,
      secondaryButton_ky: null,
      cards: [],
    },
    {
      id: "our-team",
      sectionName_ru: "Наша команда",
      sectionName_en: "Our team",
      sectionName_ky: "Биздин топ",
      heading_ru: "Ознакомьтесь с нашими специалистами",
      heading_en: "Meet our specialists",
      heading_ky: "Биздин адистер менен таанышыңыз",
      subheading_ru:
        "Наши сотрудники - это высококвалифицированные специалисты с богатым опытом в области бухгалтерии и налогового консультирования. Мы постоянно совершенствуем наши знания и следим за изменениями в законодательстве, чтобы предложить Вам самые актуальные и эффективные решения.",
      subheading_en:
        "Our employees are highly qualified specialists with extensive experience in the field of accounting and tax consulting. We constantly improve our knowledge and monitor changes in legislation in order to offer you the most relevant and effective solutions.",
      subheading_ky:
        "Биздин кызматкерлер бухгалтердик эсеп жана салык консалтинги тармагында чоң тажрыйбасы бар жогорку квалификациялуу адистер. Биз сизге эң актуалдуу жана эффективдүү чечимдерди сунуштоо үчүн билимибизди дайыма өркүндөтүп, мыйзамдардагы өзгөрүүлөргө мониторинг жүргүзүп турабыз.",
      primaryButton_ru: null,
      primaryButton_en: null,
      primaryButton_ky: null,
      secondaryButton_ru: null,
      secondaryButton_en: null,
      secondaryButton_ky: null,
      cards: [
        {
          id: "our-team-card-1",
          sectionId: "our-team",
          title_ru: "Дмитрий Сергеев",
          title_en: "Dmitry Sergeev",
          title_ky: "Дмитрий Сергеев",
          description_ru: "Директор",
          description_en: "Director",
          description_ky: "Директор",
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: "/assets/avatar/alex.jpg",
        },
        {
          id: "our-team-card-2",
          sectionId: "our-team",
          title_ru: "Анна Королева",
          title_en: "Anna Koroleva",
          title_ky: "Анна Королева",
          description_ru: "Генеральный директор",
          description_en: "CEO",
          description_ky: "Башкы директор",
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: "/assets/avatar/manager.jpg",
        },
        {
          id: "our-team-card-3",
          sectionId: "our-team",
          title_ru: "Дмитрий Сергеев",
          title_en: "Dmitry Sergeev",
          title_ky: "Дмитрий Сергеев",
          description_ru: "Директор",
          description_en: "Director",
          description_ky: "Директор",
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: "/assets/avatar/alex.jpg",
        },
        {
          id: "our-team-card-4",
          sectionId: "our-team",
          title_ru: "Анна Королева",
          title_en: "Anna Koroleva",
          title_ky: "Анна Королева",
          description_ru: "Генеральный директор",
          description_en: "CEO",
          description_ky: "Башкы директор",
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: "/assets/avatar/manager.jpg",
        },
        {
          id: "our-team-card-5",
          sectionId: "our-team",
          title_ru: "Дмитрий Сергеев",
          title_en: "Dmitry Sergeev",
          title_ky: "Дмитрий Сергеев",
          description_ru: "Директор",
          description_en: "Director",
          description_ky: "Директор",
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: "/assets/avatar/alex.jpg",
        },
        {
          id: "our-team-card-6",
          sectionId: "our-team",
          title_ru: "Анна Королева",
          title_en: "Anna Koroleva",
          title_ky: "Анна Королева",
          description_ru: "Генеральный директор",
          description_en: "CEO",
          description_ky: "Башкы директор",
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: "/assets/avatar/manager.jpg",
        },
      ],
    },
    {
      id: "our-partners",
      sectionName_ru: "Наши партнеры",
      sectionName_en: "Our partners",
      sectionName_ky: "Биздин өнөктөштөр",
      heading_ru: "Вместе мы сильнее",
      heading_en: "Together we are stronger",
      heading_ky: "Бирге биз күчтүүбүз",
      subheading_ru:
        "Мы гордимся нашими партнёрскими отношениями с ведущими компаниями и организациями. Совместная работа с нашими партнёрами позволяет нам предлагать клиентам лучшие решения и инновационные услуги.",
      subheading_en:
        "We are proud of our partners' relationships with leading companies and organizations. The collaborative work with our partners allows us to offer clients the best solutions and innovative services.",
      subheading_ky:
        "Биз алдыңкы ишканалар жана уюмдар менен өнөктөштүгүбүз менен сыймыктанабыз. Биздин өнөктөштөр менен биргелешип иштөө бизге кардарларга мыкты чечимдерди жана инновациялык кызматтарды сунуштоого мүмкүндүк берет.",
      primaryButton_ru: null,
      primaryButton_en: null,
      primaryButton_ky: null,
      secondaryButton_ru: null,
      secondaryButton_en: null,
      secondaryButton_ky: null,
      cards: [
        {
          id: "our-partners-card-1",
          sectionId: "our-partners",
          title_ru: "Компания 1",
          title_en: "Company 1",
          title_ky: "Компания 1",
          description_ru: null,
          description_en: null,
          description_ky: null,
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: "/assets/partners/1.png",
        },
        {
          id: "our-partners-card-2",
          sectionId: "our-partners",
          title_ru: "Компания 2",
          title_en: "Company 2",
          title_ky: "Компания 2",
          description_ru: null,
          description_en: null,
          description_ky: null,
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: "/assets/partners/2.png",
        },
        {
          id: "our-partners-card-3",
          sectionId: "our-partners",
          title_ru: "Компания 3",
          title_en: "Company 3",
          title_ky: "Компания 3",
          description_ru: null,
          description_en: null,
          description_ky: null,
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: "/assets/partners/3.png",
        },
        {
          id: "our-partners-card-4",
          sectionId: "our-partners",
          title_ru: "Компания 4",
          title_en: "Company 4",
          title_ky: "Компания 4",
          description_ru: null,
          description_en: null,
          description_ky: null,
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: "/assets/partners/4.png",
        },
        {
          id: "our-partners-card-5",
          sectionId: "our-partners",
          title_ru: "Компания 5",
          title_en: "Company 5",
          title_ky: "Компания 5",
          description_ru: null,
          description_en: null,
          description_ky: null,
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: "/assets/partners/5.png",
        },
      ],
    },
    {
      id: "faq",
      sectionName_ru: "Часто задаваемые вопросы",
      sectionName_en: "Frequently asked questions",
      sectionName_ky: "Көп берилүүчү суроолор",
      heading_ru: "Ищете ответы? Мы здесь, чтобы помочь!",
      heading_en: "Looking for answers? We're here to help!",
      heading_ky:
        "Жоопторду издеп жатасызбы? Биз жардам берүү үчүн бул жердебиз!",
      subheading_ru:
        "Свяжитесь с нами, если не нашли нужной информации. Мы всегда рады помочь!",
      subheading_en:
        "Contact us if you don't find the information you need. We're always here to help!",
      subheading_ky:
        "Керектүү маалыматты таппасаңыз, биз менен байланышыңыз. Биз ар дайым жардам берүүгө кубанычтабыз!",
      primaryButton_ru: null,
      primaryButton_en: null,
      primaryButton_ky: null,
      secondaryButton_ru: null,
      secondaryButton_en: null,
      secondaryButton_ky: null,
      cards: [
        {
          id: "faq-card-1",
          sectionId: "faq",
          title_ru: "В каких случаях предприниматель должен выставить ЭСФ?",
          title_en: "When should an entrepreneur apply for an ESF?",
          title_ky: "Кандай учурларда ишкер ESF чыгарышы керек?",
          description_ru:
            "Согласно постановлению правительства от 19 июня 2020 года №343, применение электронной счет-фактуры обязательно для налогоплательщика НДС и налогоплательщика, осуществляющего импорт и/или экспорт товаров.",
          description_en:
            "According to the Act of 19 June 2020, No. 343, the application of an electronic account is mandatory for the tax payer, tax payer, importer and exporter.",
          description_ky:
            "Өкмөттүн 2020-жылдын 19-июнундагы №343 токтомуна ылайык, электрондук эсеп-фактураны колдонуу КНС боюнча салык төлөөчүлөр жана товарларды импорттоочу жана/же экспорттоочу салык төлөөчүлөр үчүн милдеттүү болуп саналат.",
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: null,
        },
        {
          id: "faq-card-2",
          sectionId: "faq",
          title_ru: "В каких случаях предприниматель должен выставить ЭСФ?",
          title_en: "When should an entrepreneur apply for an ESF?",
          title_ky: "Кандай учурларда ишкер ESF чыгарышы керек?",
          description_ru:
            "Согласно постановлению правительства от 19 июня 2020 года №343, применение электронной счет-фактуры обязательно для налогоплательщика НДС и налогоплательщика, осуществляющего импорт и/или экспорт товаров.",
          description_en:
            "According to the Act of 19 June 2020, No. 343, the application of an electronic account is mandatory for the tax payer, tax payer, importer and exporter.",
          description_ky:
            "Өкмөттүн 2020-жылдын 19-июнундагы №343 токтомуна ылайык, электрондук эсеп-фактураны колдонуу КНС боюнча салык төлөөчүлөр жана товарларды импорттоочу жана/же экспорттоочу салык төлөөчүлөр үчүн милдеттүү болуп саналат.",
          extra_ru: null,
          extra_en: null,
          extra_ky: null,
          bullets_ru: [],
          bullets_en: [],
          bullets_ky: [],
          image: null,
        },
      ],
    },
  ]

  for (const section of sections) {
    const { cards, ...rest } = section
    const sectionInDB = await prisma.section.upsert({
      where: { id: section.id },
      update: {
        // No operation update
      },
      create: rest,
    })

    if (cards.length > 0) {
      for (const card of cards) {
        await prisma.card.upsert({
          where: { sectionId_id: { sectionId: sectionInDB.id, id: card.id } },
          update: {
            // No operation update
          },
          create: { ...card, sectionId: sectionInDB.id },
        })
      }
    }
  }

  console.log("Sections have been seeded.")
}

async function seedAdminUser() {
  const adminEmail = process.env.ADMIN_EMAIL
  const adminPassword = process.env.ADMIN_PASSWORD

  if (!adminEmail || !adminPassword) {
    throw new Error(
      "ADMIN_EMAIL and ADMIN_PASSWORD must be set in environment variables.",
    )
  }

  await prisma.user.upsert({
    where: { email: adminEmail },
    update: {
      // No operation update
    },
    create: {
      name: "Admin",
      email: adminEmail,
      password: adminPassword,
      role: "ADMIN",
    },
  })

  console.log("Admin user has been seeded.")
}

async function main() {
  await seedSections()
  await seedAdminUser()
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async e => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
